services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # 更新到宿主机 docker GID
        DOCKER_GID: 999  # 请根据宿主机上的docker组GID调整这个值
    ports:
      - 3080:3080               # Change it to 9000:3080 to use nginx
      - 3090:3090               # Frontend dev server port
    extra_hosts: # if you are running APIs on docker you need access to, you will need to uncomment this line and next
    - "host.docker.internal:host-gateway"

    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspaces:cached
      # 挂载Docker套接字，用于Docker-outside-of-Docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://host.docker.internal:27017/LibreChat
      # - CHATGPT_REVERSE_PROXY=http://host.docker.internal:8080/api/conversation # if you are hosting your own chatgpt reverse proxy with docker
      # - OPENAI_REVERSE_PROXY=http://host.docker.internal:8070/v1/chat/completions # if you are hosting your own chatgpt reverse proxy with docker
      # - MEILI_HOST=http://meilisearch:7700

    # Runs app on the same network as the service container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:another-service
    
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # Use a non-root user for all processes - See https://aka.ms/vscode-remote/containers/non-root for details.
    user: vscode

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  

